<ul class="menu">
	<li class="first leaf">
		<a target="_blank" title="" href="mailto:<?php echo Application_Model_Object_Parametre::find('prm_code = \'mail_webmaster\' ')->getValeur()?>" class="contactMail">contacter le webmaster du site</a>
	</li>
	<li class="leaf">
		INTERNE ORANGE
	</li>
	<li class="last leaf">
		<a title="" href="mailto:<?php echo Application_Model_Object_Parametre::find('prm_code = \'mail_equipe\'')->getValeur()?>" class="contactMail">contacter l'équipe communication du domaine</a>
	</li>
</ul>