<?php echo $this->doctype() ?>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<link href="/images/favicon.ico" type="image/x-icon" rel="shortcut icon"> 
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <!--[if lt IE 9]>
	<script src="/js/library/html5shiv.js"></script>
	<script src="/js/library/IE9.js"></script>
	<![endif]-->
</head>
<body>
	<header>
		<?php echo $this->partial('common/header.phtml');?>		
	</header>
	
	<?php echo $this->action('index','Navigation'); ?>

	<div id="content">  
    	<?php echo $this->layout()->content ?>
    	<div class="clear"></div>
    </div>
    
    <footer>
		<?php echo $this->partial('common/footer.phtml');?>
	</footer>	
</body>
</html>	